"""Non-model constants for the songmaker CLI."""

from __future__ import annotations

import datetime

OUTPUT_ROOT = "_output"
DEFAULT_ARTIST = "Flex0r"
SIMILARITY_GOOD = 0.8
SIMILARITY_FAIR = 0.5

# Scoring pipeline
SILENCE_LONGEST_GAP_PENALTY = 10.0
SILENCE_LONGEST_GAP_MAX_PENALTY = 50.0
SILENCE_GAP_COUNT_PENALTY = 5.0
SILENCE_GAP_COUNT_MAX_PENALTY = 30.0
SILENCE_TOP_DB = 40
SILENCE_MIN_GAP_SECONDS = 2.0
SILENCE_TRIM_SECONDS = 2.0
BPM_DEVIATION_PENALTY = 5.0
BPM_OCTAVE_ERROR_TOLERANCE = 0.05
SCORING_SAMPLE_RATE = 22050
SCORING_NUM_SECTIONS = 6
DYNAMICS_PITCH_WEIGHT = 0.4
DYNAMICS_RMS_WEIGHT = 0.3
DYNAMICS_ONSET_WEIGHT = 0.3


def default_year() -> str:
    return str(datetime.date.today().year)
