"""add share fields to songs and generations

Revision ID: 93236a097220
Revises: c3d5e7f91234
Create Date: 2026-03-31 12:57:56.390628

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '93236a097220'
down_revision: Union[str, Sequence[str], None] = 'c3d5e7f91234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('share_slug', sa.String(length=36), nullable=True))
    op.add_column('generations', sa.Column(
        'is_shared', sa.Boolean(), nullable=False,
        server_default=sa.text('false'),
    ))
    op.create_index(op.f('ix_generations_share_slug'), 'generations', ['share_slug'], unique=True)
    op.add_column('songs', sa.Column('share_slug', sa.String(length=36), nullable=True))
    op.add_column('songs', sa.Column(
        'is_shared', sa.Boolean(), nullable=False,
        server_default=sa.text('false'),
    ))
    op.create_index(op.f('ix_songs_share_slug'), 'songs', ['share_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_share_slug'), table_name='songs')
    op.drop_column('songs', 'is_shared')
    op.drop_column('songs', 'share_slug')
    op.drop_index(op.f('ix_generations_share_slug'), table_name='generations')
    op.drop_column('generations', 'is_shared')
    op.drop_column('generations', 'share_slug')
    # ### end Alembic commands ###
